# Generated by Django 5.0.4 on 2024-04-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_about_features_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('cause', models.TextField()),
                ('treatment', models.TextField()),
                ('prevention', models.TextField()),
            ],
        ),
    ]
