# Generated by Django 5.0.4 on 2024-04-13 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0006_remove_testimonial_name_testimonial_date_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='date_submitted',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
